apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: 4005
      targetPort: 4005
      nodePort: 32001